env:
  global:
  - GCP_PROJECT_ID=eksamen-devops
  - tf_version=0.12.19
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: Yu6dBs8V2XOOxjY4nvzMRWJWydskOOjySKe8KCtEyaprDj1V0pcvlfKLTRej6E9vVVLInR7mpIgm/aUIYLvDu3Soz3Jz6BjHvrLDuUKRZXafEMMy636mD+EAy2qbvqVQByQVTvAKev+rJN85pGg1cuY7SPqYHVCdzQ8Bor+sXA6Ts2DWlPFXMOW0Est3m3uD5T92OigE79sGPM5i1+AHXf+4N12Cvy263dlrojeZD2br8eAYEANFHnrDVf9BhMgSrub7WKUND7Qf4tcuAA2haPKMWd71MvvN6V2I8u4yryT8d53Lr1J8vh/MMZqbQrVVyyf0tLmd/Ch45HwcYVIqawgl2JQYyLj4GiAvlZD267urVj9dPLm6U05CLBKV90tS0L+xm4da0Qn914AeymFfO+A8QBjVj4Eg5+slAKWp4t9gV5+pT1BwPd7Psk8bxUF9JItq7xwkvM0pxaqHr90v+kIuUyFIM1rIL8C0jXfhRr22BcE/XGR+87RH0vvk+WMhnBnJqcuxHvIp7DXLvQUnoIJxQfzOfOVylWGgyYzm3zp9qht/iPCZbfEBLPleeR6FUmvoBHkaz+sxm0ucDzKItuRc/vE20+aPE7TbAxfJJOKT9GlYaQAiZiYmOd29sSa3Jd2rJsXZoYbFKuE5yqJGS8VBX1gyPTbX3VimeC8jVsE=
  - secure: pLLmwcP0lKN12zrubv9I7zuXWJ7jTS+miE8VZJvfPve0L7w34K8PPUG6gphuM79wUz1m2Vt2R7yIZz+lYKAItkMB8jdwtnWbkvhWuAlH1cqkjZhf2ft61XHB86CfGb9ix0OiOuIsatnBOEDqJXv58jk5aD4XaVvAeVrXSNMu6WZM/AL23FhbH4rkD7P7O+JyNJ87A+Wuuabtdio7n/oF8lQfgONaZAeUg8qCrbvHsV/byGOjcNqEQM9BZzFmBLkJ1aT3ZmekCE4g5TsupB2Oly7TroBVVw/O7vU/yR7HUMB6TmyDh9U8JIVbM4AA1GuvoVZwyRgJyDWK0S92VjQWZyBCyyhyHsZhRVp06tCqJU98Zae1zATdNiuZFFBHm9utCZds6U1ohrbmsb4AV93GjJ2jodxljTiOR4pCfFkWPfhgJHTJhD9+QT1x1iJQMjq/tiL4TcVetajwJ4S4Lq+4Hdg3+3+9Jkv2hHOtN6Cr2m+gVdyAGqvOWNI7Csd2PmBhiqHD0fiPMERpeADCIi10TGSk58VY2tceltY12UgP96ufES1lx7ING7bmu1h/bK+zJ1EJgA9KSkwbt0Vj1DjfmSGGt0g4iuzv1OyUDmcIvvksULE2P76tLkPc582gKcJpjDk0b1cJUtBgpnL2F3dqpC2nROpmrc2E1iFAlhYpPO0=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_40d97da57ddf_key -iv $encrypted_40d97da57ddf_iv
  -in eksamen-devops-f7bc3c2f300a.json.enc -out eksamen-devops-f7bc3c2f300a.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=eksamen-devops-f7bc3c2f300a.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./eksamen-devops-f7bc3c2f300a.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
